name: CI/CD

on: push

jobs:
  front_test:
    runs-on: ubuntu-latest
    steps:
      # 最新のbranchへ移動
      - name: Checkout latest branch
        uses: actions/checkout@v3

      # Node.js環境を作成
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: yarn build & install
        working-directory: ./frontend
        env:
          VITE_RAILS_API_DOMEIN: ${{ secrets.VITE_RAILS_API_DOMEIN }}
        run: |
          yarn install
          yarn build

      - name: Run Front Test
        working-directory: ./frontend
        run: yarn test
